version: '3.3'

services:
  py:
    depends_on:
      - db
    build: ./flask/
    #* Fazendo uso de Bind Mount, onde persistimos nas alterações
    #* sem necessitar ficar dando o comando do compose up
    volumes:
      - "/mnt/c/Users/rodri/dev/api-py-mysql-docker/flask:/app"
    ports:
      - 5000:5000
    networks:
      - networkdocker

  db:
    build: ./mysql/
    ports:
      - 3306:3306
    env_file:
      - ./config/db.env
    volumes:
      - './mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql'
    networks:
      - networkdocker

networks:
  networkdocker: