version: '3.3'

services:
  py:
    depends_on:
      - db
    build: ./flask/
    ports:
      - 5000:5000
    networks:
      - networkdocker

  db:
    build: ./mysql/
    ports:
      - 3306:3306
    env_file:
      - ./config/db.env
    volumes:
      - './mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql'
    networks:
      - networkdocker

networks:
  networkdocker: